development:
  adapter: postgresql
  database: fbTicketDev
  encoding: unicode
  pool: 16
  username: su
  password: su
  host: localhost
  
test: &TEST
  adapter: postgresql
  database: fbTicketTest
  encoding: unicode
  pool: 16
  username: su
  password: su
  host: localhost

production:
  adapter: postgresql
  database: fbTicket
  pool: 16
  encoding: su
  username: su
  password: su
  host: localhost
  
cucumber:
  <<: *TEST

